### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by codeman256** [pcb2gcode/pcb2gcodeGUI#6] opened 2016-09-28 04:16 UTC
I tried compiling and it is not working.

git clone:
cd pcb2gcodeGUI:
qmake; displays nothing?
make; display:>>
/usr/lib/arm-linux-gnueabihf/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h
/usr/lib/arm-linux-gnueabihf/qt5/bin/uic outputwindow.ui -o ui_outputwindow.h
/usr/lib/arm-linux-gnueabihf/qt5/bin/uic cmdlineargs.ui -o ui_cmdlineargs.h
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSvg -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -o main.o main.cpp
In file included from mainwindow.h:39:0,
                 from main.cpp:20:
argaction.h: In member function ‘bool argAction::setValue(QString, QString)’:
argaction.h:92:9: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
         auto pos = objects.find(key);
         ^
argaction.h:92:14: error: ‘pos’ does not name a type
         auto pos = objects.find(key);
              ^
argaction.h:94:13: error: ‘pos’ was not declared in this scope
         if (pos != objects.end())
             ^
argaction.h: At global scope:
argaction.h:90:40: warning: unused parameter ‘key’ [-Wunused-parameter]
     inline bool setValue(const QString key, const QString value)
                                        ^
Makefile:366: recipe for target 'main.o' failed
make: **\* [main.o] Error 1

**Comment by corna** [comment] 2016-09-28 07:50
Duplicate of #5 

(if qmake displays nothing it means that everything is ok)

**Closed as completed by corna** 2016-09-28 07:50 UTC
